# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Knowledge Base: Autotools Integration"
email: autotools-support@mergesium.com
description: > # this means to ignore newlines until "baseurl:"
  The knowledge base supplements the VSCode extension <a href='https://marketplace.visualstudio.com/items?itemName=mergesium.autotools'>Mergesium Autotools Integration</a>
  with up-to-date workarounds for issues discovered after release.
baseurl: "/kb"
url: "https://autotools.mergesium.com"
twitter_username: mergesium
github_username:  Mergesium

permalink: /:title:output_ext

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
  hard_wrap: false
